# Generated by Django 4.2.1 on 2023-06-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_getouch_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_model',
            name='image',
            field=models.ImageField(default=None, upload_to='media'),
        ),
    ]
