# Generated by Django 4.2.1 on 2023-06-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_login_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_model',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='media'),
        ),
    ]
