# Generated by Django 4.2.1 on 2023-06-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_login_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_model',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
