# Generated by Django 4.2.1 on 2023-06-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_alter_login_model_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=8)),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='login_model',
        ),
    ]
