# Generated by Django 4.2.1 on 2023-06-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_login_model_delete_seller_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_model',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
