# Generated by Django 4.2.1 on 2023-06-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0022_alter_login_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_model',
            name='image',
        ),
        migrations.AddField(
            model_name='login_model',
            name='pic',
            field=models.ImageField(default='pic', null=True, upload_to='media/'),
        ),
    ]
