# Generated by Django 4.2.1 on 2023-06-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0025_seller_model_delete_login_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_model',
            name='pic',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
