# Generated by Django 4.2.1 on 2023-06-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_alter_seller_model_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(max_length=100)),
                ('p_size', models.IntegerField()),
                ('p_dis', models.CharField(max_length=500)),
                ('p_img', models.FileField(null=True, upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='seller_model',
        ),
    ]
