# Generated by Django 4.2.1 on 2023-06-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0028_product_detail_delete_seller_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_detail',
            name='p_img',
        ),
    ]
